// packages/create-scaffa/templates/vue/src/modules/home/HomeView.vue
<template>
  <div class="container py-6">
    <!-- Hero Section -->
    <div class="flex flex-col items-center text-center space-y-4 py-12">
      <h1 class="text-4xl font-bold tracking-tight lg:text-6xl">
        Welcome to
        <span class="text-primary">Scaffa Vue</span>
      </h1>
      <p class="text-xl text-muted-foreground max-w-2xl">
        A modern Vue.js starter template with TypeScript, Tailwind CSS, shadcn-vue components, and
        best practices built-in.
      </p>
      <div class="flex gap-4 mt-6">
        <Button size="lg" @click="$router.push('/dashboard')"> Get Started </Button>
        <Button variant="outline" size="lg" @click="$router.push('/products')">
          View Products
        </Button>
      </div>
    </div>

    <!-- Features Grid -->
    <div class="grid gap-6 md:grid-cols-2 lg:grid-cols-3 py-12">
      <Card class="p-6">
        <div class="flex items-center gap-4 mb-4">
          <div class="h-12 w-12 rounded-lg bg-primary/10 flex items-center justify-center">
            <Palette class="h-6 w-6 text-primary" />
          </div>
          <h3 class="text-lg font-semibold">Beautiful UI</h3>
        </div>
        <p class="text-muted-foreground">
          Pre-built components using shadcn-vue and Tailwind CSS for beautiful, accessible
          interfaces.
        </p>
      </Card>

      <Card class="p-6">
        <div class="flex items-center gap-4 mb-4">
          <div class="h-12 w-12 rounded-lg bg-primary/10 flex items-center justify-center">
            <Zap class="h-6 w-6 text-primary" />
          </div>
          <h3 class="text-lg font-semibold">Fast Development</h3>
        </div>
        <p class="text-muted-foreground">
          Hot module replacement, TypeScript support, and modern build tools for rapid development.
        </p>
      </Card>

      <Card class="p-6">
        <div class="flex items-center gap-4 mb-4">
          <div class="h-12 w-12 rounded-lg bg-primary/10 flex items-center justify-center">
            <Shield class="h-6 w-6 text-primary" />
          </div>
          <h3 class="text-lg font-semibold">Type Safe</h3>
        </div>
        <p class="text-muted-foreground">
          Full TypeScript integration with proper type definitions and compile-time error checking.
        </p>
      </Card>

      <Card class="p-6">
        <div class="flex items-center gap-4 mb-4">
          <div class="h-12 w-12 rounded-lg bg-primary/10 flex items-center justify-center">
            <Globe class="h-6 w-6 text-primary" />
          </div>
          <h3 class="text-lg font-semibold">Internationalization</h3>
        </div>
        <p class="text-muted-foreground">
          Built-in i18n support with Vue I18n for multi-language applications.
        </p>
      </Card>

      <Card class="p-6">
        <div class="flex items-center gap-4 mb-4">
          <div class="h-12 w-12 rounded-lg bg-primary/10 flex items-center justify-center">
            <Database class="h-6 w-6 text-primary" />
          </div>
          <h3 class="text-lg font-semibold">State Management</h3>
        </div>
        <p class="text-muted-foreground">
          Pinia for state management and TanStack Query for server state management.
        </p>
      </Card>

      <Card class="p-6">
        <div class="flex items-center gap-4 mb-4">
          <div class="h-12 w-12 rounded-lg bg-primary/10 flex items-center justify-center">
            <Smartphone class="h-6 w-6 text-primary" />
          </div>
          <h3 class="text-lg font-semibold">Responsive</h3>
        </div>
        <p class="text-muted-foreground">
          Mobile-first responsive design that works beautifully on all device sizes.
        </p>
      </Card>
    </div>

    <!-- API Demo Section -->
    <div class="py-12 border-t">
      <div class="text-center mb-8">
        <h2 class="text-3xl font-bold">API Integration Demo</h2>
        <p class="text-muted-foreground mt-2">
          Test the built-in API integration with TanStack Query
        </p>
      </div>

      <div class="grid gap-6 md:grid-cols-2">
        <Card class="p-6">
          <CardHeader>
            <CardTitle class="flex items-center gap-2">
              <Globe class="h-5 w-5" />
              Language Switcher
            </CardTitle>
            <CardDescription> {{ t('common.hello') }} - Switch between languages </CardDescription>
          </CardHeader>
          <CardContent>
            <div class="flex gap-2">
              <Button
                variant="outline"
                @click="changeLanguage('en')"
                :class="{ 'border-black dark:border-red-200': locale === 'en' }"
              >
                English
              </Button>
              <Button
                variant="outline"
                @click="changeLanguage('mm')"
                :class="{ 'border-black dark:border-red-200': locale === 'mm' }"
              >
                Myanmar
              </Button>
            </div>
          </CardContent>
        </Card>

        <Card class="p-6">
          <CardHeader>
            <CardTitle class="flex items-center gap-2">
              <Package class="h-5 w-5" />
              Quick Add Product
            </CardTitle>
            <CardDescription> Add a new product to test the API integration </CardDescription>
          </CardHeader>
          <CardContent>
            <div class="space-y-3">
              <Input v-model="input" placeholder="Enter product name..." :disabled="isPending" />
              <Button @click="addProduct" :disabled="isPending || !input" class="w-full">
                {{ isPending ? 'Adding...' : 'Add Product' }}
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>

      <!-- Products List -->
      <Card class="mt-8">
        <CardHeader>
          <CardTitle class="flex items-center gap-2">
            <Package class="h-5 w-5" />
            Recent Products ({{ data?.length || 0 }})
          </CardTitle>
          <CardDescription> Products loaded from the API </CardDescription>
        </CardHeader>
        <CardContent>
          <div v-if="isLoading" class="space-y-2">
            <Skeleton class="h-12 w-full" />
            <Skeleton class="h-12 w-full" />
            <Skeleton class="h-12 w-full" />
          </div>
          <div v-else class="space-y-2 max-h-64 overflow-y-auto">
            <div
              v-for="(product, index) in data?.slice(0, 10)"
              :key="product.id"
              class="flex items-center gap-3 p-3 rounded-lg border hover:bg-accent/50 transition-colors"
            >
              <div class="h-10 w-10 rounded-lg bg-primary/10 flex items-center justify-center">
                <span class="text-sm font-semibold">{{ index + 1 }}</span>
              </div>
              <div class="flex-1">
                <p class="font-medium">{{ product.title }}</p>
                <p class="text-sm text-muted-foreground">{{ product.category }}</p>
              </div>
              <Badge variant="secondary">${{ product.price }}</Badge>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useQueryClient } from '@tanstack/vue-query'
import { useI18n } from 'vue-i18n'
import { toast } from 'vue-sonner'
import api from '@/api'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Skeleton } from '@/components/ui/skeleton'
import Button from '@/components/ui/button/Button.vue'
import Input from '@/components/ui/input/Input.vue'
import { Palette, Zap, Shield, Globe, Database, Smartphone, Package } from 'lucide-vue-next'

const { t, locale } = useI18n()
const queryClient = useQueryClient()

const changeLanguage = (lang: string) => {
  locale.value = lang
  localStorage.setItem('scaffa-locale', lang)
}

const { data, isLoading } = api.products.getProducts.useQuery()
const input = ref('')

const { mutate, isPending } = api.products.addProduct.useMutation({
  onSuccess: (product) => {
    queryClient.setQueryData(['products'], (oldData: ProductType[]) => {
      return [...(oldData || []), product]
    })
    input.value = ''
    toast.success('Product added successfully!')
  },
  onError: () => {
    toast.error('Failed to add product')
  },
})

const addProduct = () => {
  if (!input.value) return
  mutate({
    title: input.value,
    description: 'Sample product description',
    category: 'Sample Category',
    price: 29.99,
    discountPercentage: 10,
    rating: 4.5,
    stock: 100,
    tags: ['sample', 'demo'],
    brand: 'Sample Brand',
    sku: `SKU${Date.now()}`,
    weight: 0.5,
    dimensions: {
      width: 10,
      height: 10,
      depth: 5,
    },
  })
}
</script>

// packages/create-scaffa/templates/react/colorful/src/modules/home/HomeView.tsx
import api from '@/api';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Languages, Plus, Package, ListTodo, Loader2 } from 'lucide-react';
import i18next from 'i18next';

const HomeView = () => {
	const { t } = useTranslation();
	const [input, setInput] = useState('');
	const queryClient = useQueryClient();

	const changeLanguage = (lng: string) => {
		i18next.changeLanguage(lng);
		localStorage.setItem('scaffa-locale', lng);
	};

	const productsQuery = api.products.getProducts.useQuery();
	const todosQuery = api.todos.getTodos.useInfiniteQuery();

	const addProductMutation = api.products.addProduct.useMutation({
		onSuccess: (data) => {
			toast.success('Product added successfully');
			queryClient.setQueryData(['products'], (oldData: ProductType[]) => [
				...(oldData ?? []),
				data
			]);
			setInput('');
		}
	});

	const addProduct = () => {
		if (!input) {
			toast.error('Please enter a product name');
			return;
		}
		addProductMutation.mutate({
			title: input,
			description: 'Test',
			category: 'Test',
			price: 129.99,
			discountPercentage: 15,
			rating: 4.5,
			stock: 200,
			tags: ['test', 'testing'],
			brand: 'TestBrand',
			sku: 'TestSKU123',
			weight: 0.3,
			dimensions: {
				width: 18,
				height: 20,
				depth: 8
			}
		});
	};

	return (
		<div className="max-w-4xl mx-auto p-6 space-y-8 text-sm">
			{/* Header */}
			<div>
				<h1 className="text-2xl font-bold flex items-center gap-2">
					<Package className="w-6 h-6 text-primary" />
					Scaffa Colorful
				</h1>
				<p className="text-muted-foreground">Tech Stack: React + ShadCN UI</p>
				<p>{t('common.hello')}</p>
			</div>

			{/* Language Switch */}
			<div className="flex items-center gap-2">
				<Languages className="w-5 h-5 text-muted-foreground" />
				<Button variant="outline" onClick={() => changeLanguage('en')}>
					English
				</Button>
				<Button variant="outline" onClick={() => changeLanguage('mm')}>
					Myanmar
				</Button>
			</div>

			{/* Add Product */}
			<div className="bg-muted p-4 rounded-md space-y-3">
				<p className="font-medium flex items-center gap-2">
					<Plus className="w-4 h-4" /> Add a new product
				</p>
				<div className="flex gap-2">
					<Input
						disabled={addProductMutation.isPending}
						className="w-full"
						placeholder="Product Name"
						value={input}
						onChange={(e) => setInput(e.target.value)}
					/>
					<Button
						disabled={addProductMutation.isPending}
						onClick={addProduct}
						className="flex items-center gap-1"
					>
						{addProductMutation.isPending && <Loader2 className="w-4 h-4 animate-spin" />}
						<Plus className="w-4 h-4" />
						Add
					</Button>
				</div>
			</div>

			{/* Product List */}
			<div>
				<h2 className="text-lg font-semibold mb-4 flex items-center gap-2">
					<Package className="w-5 h-5" />
					Products
				</h2>
				{productsQuery.isLoading ? (
					<p className="text-muted-foreground">Loading...</p>
				) : (
					<div className="grid sm:grid-cols-2 md:grid-cols-3 gap-4 max-h-64 overflow-y-auto pr-2">
						{productsQuery.data?.map((item) => (
							<div
								key={item.id}
								className="bg-card border border-border rounded-lg p-4 shadow-sm flex flex-col gap-1"
							>
								<div className="flex items-center justify-between">
									<h3 className="font-medium">{item.title}</h3>
									<Package className="w-4 h-4 text-muted-foreground" />
								</div>
								<p className="text-xs text-muted-foreground">SKU: {item.sku || 'N/A'}</p>
								<p className="text-xs">Stock: {item.stock}</p>
								<p className="text-xs">Price: ${item.price}</p>
							</div>
						))}
					</div>
				)}
			</div>

			{/* Todos List */}
			<div>
				<h2 className="text-lg font-semibold mb-4 flex items-center gap-2">
					<ListTodo className="w-5 h-5" />
					Todos
				</h2>
				{todosQuery.data?.length === 0 ? (
					<p className="text-muted-foreground">No todos found.</p>
				) : (
					<div className="flex flex-col gap-2 max-h-52 overflow-y-auto pr-2">
						{todosQuery.data?.map((todo) => (
							<div
								key={todo.id}
								className="bg-card border border-border rounded-md p-3 flex items-start gap-2 shadow-sm"
							>
								<ListTodo className="w-4 h-4 mt-1 text-primary" />
								<span className="text-sm">{todo.todo}</span>
							</div>
						))}
					</div>
				)}

				<div className="mt-3">
					{todosQuery.hasNextPage ? (
						<Button variant="outline" onClick={() => todosQuery.fetchNextPage()}>
							Load More
						</Button>
					) : (
						<p className="text-muted-foreground text-xs italic">No more data...</p>
					)}
				</div>
			</div>
		</div>
	);
};

export default HomeView;
