// packages/create-scaffa/templates/react/colorful/src/modules/todos/TodosView.tsx
'use client';

import api from '@/api';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { Input } from '@/components/ui/input';
import { ListTodo, Trash2, Pencil, Plus, CheckCircle } from 'lucide-react';
import { useState, useMemo } from 'react';
import { TodoModal, TaskForm } from '@/components/TodoModal';
import { Select } from '@/components/ui/select';
import { SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { getPriorityBadgeVariant, getStatusBadgeVariant } from '@/utils/todoBadgeUtils';
import { toast } from 'sonner';
import { useQueryClient } from '@tanstack/react-query';

type StatusType = 'Pending' | 'In Progress' | 'Completed';
type PriorityType = 'Low' | 'Medium' | 'High';

const TodosView = () => {
	const [search, setSearch] = useState('');
	const [modalOpen, setModalOpen] = useState(false);
	const [editingTodo, setEditingTodo] = useState<TaskForm | null>(null);
	const [filterStatus, setFilterStatus] = useState<StatusType | 'All'>('All');
	const [filterPriority, setFilterPriority] = useState<PriorityType | 'All'>('All');

	const queryClient = useQueryClient();
	const todosQuery = api.todos.getTodos.useInfiniteQuery();
	const addMutation = api.todos.addTodo.useMutation();
	const updateMutation = api.todos.updateTodo.useMutation();
	const deleteMutation = api.todos.deleteTodo.useMutation();

	const todos = useMemo(
		() =>
			todosQuery.data?.map((todo, index) => ({
				...todo,
				status: ['Pending', 'In Progress', 'Completed'][index % 3] as StatusType,
				priority: ['Low', 'Medium', 'High'][index % 3] as PriorityType
			})) ?? [],
		[todosQuery.data]
	);

	const filteredTodos = useMemo(() => {
		return todos.filter((todo) => {
			const matchesSearch = todo.todo.toLowerCase().includes(search.toLowerCase());
			const matchesStatus = filterStatus === 'All' || todo.status === filterStatus;
			const matchesPriority = filterPriority === 'All' || todo.priority === filterPriority;
			return matchesSearch && matchesStatus && matchesPriority;
		});
	}, [todos, search, filterStatus, filterPriority]);

	const statusToFormStatus = (status: StatusType): TaskForm['status'] => {
		const map: Record<StatusType, TaskForm['status']> = {
			'Pending': 'Todo',
			'In Progress': 'In Progress',
			'Completed': 'Done'
		};
		return map[status];
	};

	const handleEdit = (todo: (typeof todos)[number]) => {
		setEditingTodo({
			id: todo.id.toString(),
			title: todo.todo,
			description: '',
			status: statusToFormStatus(todo.status),
			priority: todo.priority
		});
		setModalOpen(true);
	};

	const handleDelete = (id: number) => {
		if (confirm('Are you sure you want to delete this task?')) {
			deleteMutation.mutate(id, {
				onSuccess: () => {
					toast.success('Task deleted successfully');
					queryClient.invalidateQueries({ queryKey: ['todos'] });
				},
				onError: () => {
					toast.error('Failed to delete task');
				}
			});
		}
	};

	const handleToggleComplete = (todo: (typeof todos)[number]) => {
		const isCompleted = todo.status === 'Completed';
		updateMutation.mutate(
			{ id: todo.id, data: { completed: !isCompleted } },
			{
				onSuccess: () => {
					toast.success(`Task marked as ${!isCompleted ? 'completed' : 'pending'}`);
					queryClient.invalidateQueries({ queryKey: ['todos'] });
				},
				onError: () => {
					toast.error('Failed to update task status');
				}
			}
		);
	};

	const handleSubmit = (task: TaskForm) => {
		if (editingTodo && task.id) {
			updateMutation.mutate(
				{
					id: parseInt(task.id, 10),
					data: { todo: task.title, completed: task.status === 'Completed' }
				},
				{
					onSuccess: () => {
						toast.success('Task updated successfully');
						queryClient.invalidateQueries({ queryKey: ['todos'] });
						setModalOpen(false);
						setEditingTodo(null);
					},
					onError: () => {
						toast.error('Failed to update task');
					}
				}
			);
		} else {
			addMutation.mutate(
				{ todo: task.title, completed: task.status === 'Completed', userId: 1 },
				{
					onSuccess: () => {
						toast.success('Task created successfully');
						queryClient.invalidateQueries({ queryKey: ['todos'] });
						setModalOpen(false);
						setEditingTodo(null);
					},
					onError: () => {
						toast.error('Failed to create task');
					}
				}
			);
		}
	};

	const handleOpenNewTask = () => {
		setEditingTodo(null);
		setModalOpen(true);
	};

	return (
		<div className="p-6 space-y-6">
			{/* Header */}
			<div className="space-y-1">
				<h2 className="text-2xl font-bold flex items-center gap-2">
					<ListTodo className="w-6 h-6 text-primary" />
					Tasks
				</h2>
				<p className="text-muted-foreground text-sm">Here’s a list of your tasks this month</p>
			</div>

			{/* Top Filters */}
			<div className="flex flex-col sm:flex-row items-center justify-between gap-4">
				<div className="flex gap-2 w-full sm:w-auto">
					<Input
						placeholder="Search tasks..."
						value={search}
						onChange={(e) => setSearch(e.target.value)}
						className="w-full sm:w-[240px]"
					/>
					<Select onValueChange={(v) => setFilterStatus(v as StatusType | 'All')}>
						<SelectTrigger className="w-[150px]">
							<SelectValue placeholder="Status" />
						</SelectTrigger>
						<SelectContent>
							<SelectItem value="All">All Statuses</SelectItem>
							<SelectItem value="Pending">Pending</SelectItem>
							<SelectItem value="In Progress">In Progress</SelectItem>
							<SelectItem value="Completed">Completed</SelectItem>
						</SelectContent>
					</Select>
					<Select onValueChange={(v) => setFilterPriority(v as PriorityType | 'All')}>
						<SelectTrigger className="w-[150px]">
							<SelectValue placeholder="Priority" />
						</SelectTrigger>
						<SelectContent>
							<SelectItem value="All">All Priorities</SelectItem>
							<SelectItem value="Low">Low</SelectItem>
							<SelectItem value="Medium">Medium</SelectItem>
							<SelectItem value="High">High</SelectItem>
						</SelectContent>
					</Select>
				</div>
				<Button onClick={handleOpenNewTask}>
					<Plus className="w-4 h-4 mr-2" />
					New Task
				</Button>
			</div>

			{/* Task Table */}
			<div className="rounded-lg border bg-card shadow-sm overflow-hidden">
				<div className="overflow-x-auto">
					<table className="w-full text-sm">
						<thead className="border-b bg-muted/50">
							<tr className="text-muted-foreground">
								<th className="px-4 py-3 text-left">ID</th>
								<th className="px-4 py-3 text-left">Title</th>
								<th className="px-4 py-3 text-left">Status</th>
								<th className="px-4 py-3 text-left">Priority</th>
								<th className="px-4 py-3 text-right">Actions</th>
							</tr>
						</thead>
						<tbody>
							{todosQuery.isLoading ? (
								Array.from({ length: 6 }).map((_, i) => (
									<tr key={i} className="border-b">
										<td colSpan={5} className="px-4 py-3">
											<Skeleton className="h-4 w-full" />
										</td>
									</tr>
								))
							) : filteredTodos.length > 0 ? (
								filteredTodos.map((todo) => (
									<tr key={todo.id} className="border-b hover:bg-muted/40 transition">
										<td className="px-4 py-3 text-primary font-medium">TASK-{todo.id}</td>
										<td className="px-4 py-3">{todo.todo}</td>
										<td className="px-4 py-3">
											<Badge variant={getStatusBadgeVariant(todo.status)}>{todo.status}</Badge>
										</td>
										<td className="px-4 py-3">
											<Badge variant={getPriorityBadgeVariant(todo.priority)}>
												{todo.priority}
											</Badge>
										</td>
										<td className="px-4 py-3 text-right flex justify-end gap-2">
											<Button variant="ghost" size="icon" onClick={() => handleToggleComplete(todo)}>
												<CheckCircle className={`w-4 h-4 ${todo.status === 'Completed' ? 'text-green-500' : 'text-gray-400'}`} />
											</Button>
											<Button variant="ghost" size="icon" onClick={() => handleEdit(todo)}>
												<Pencil className="w-4 h-4" />
											</Button>
											<Button variant="ghost" size="icon" onClick={() => handleDelete(todo.id)}>
												<Trash2 className="w-4 h-4 text-red-500" />
											</Button>
										</td>
									</tr>
								))
							) : (
								<tr>
									<td colSpan={5} className="text-center text-muted-foreground py-6">
										No tasks found.
									</td>
								</tr>
							)}
						</tbody>
					</table>
				</div>
			</div>

			{/* Load More */}
			{todosQuery.hasNextPage && (
				<div className="flex justify-center pt-4">
					<Button onClick={() => todosQuery.fetchNextPage()} variant="outline">
						Load More
					</Button>
				</div>
			)}

			{/* Modal */}
			<TodoModal
				isOpen={modalOpen}
				onClose={() => {
					setModalOpen(false);
					setEditingTodo(null);
				}}
				initialData={editingTodo || undefined}
				onSubmit={handleSubmit}
			/>
		</div>
	);
};

export default TodosView;

// packages/create-scaffa/templates/vue/src/modules/todos/TodosView.vue
<template>
  <div class="container py-6">
    <div class="flex flex-col space-y-4">
      <div class="flex items-center justify-between">
        <div>
          <h1 class="text-3xl font-bold">Todo List</h1>
          <p class="text-muted-foreground">Manage your tasks and stay organized</p>
        </div>
        <Button @click="openAddModal">
          <Plus class="mr-2 h-4 w-4" />
          Add Todo
        </Button>
      </div>

      <div class="grid gap-4 md:grid-cols-3">
        <Card>
          <CardHeader>
            <CardTitle class="text-sm font-medium text-muted-foreground">Total Tasks</CardTitle>
          </CardHeader>
          <CardContent>
            <div class="text-2xl font-bold">{{ todos.length }}</div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle class="text-sm font-medium text-muted-foreground">Completed</CardTitle>
          </CardHeader>
          <CardContent>
            <div class="text-2xl font-bold text-green-600">{{ completedTodos.length }}</div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle class="text-sm font-medium text-muted-foreground">Pending</CardTitle>
          </CardHeader>
          <CardContent>
            <div class="text-2xl font-bold text-orange-600">{{ pendingTodos.length }}</div>
          </CardContent>
        </Card>
      </div>

      <div class="grid gap-4 md:grid-cols-2">
        <!-- Pending Todos -->
        <Card>
          <CardHeader>
            <CardTitle class="flex items-center gap-2">
              <Clock class="h-5 w-5" />
              Pending Tasks
            </CardTitle>
          </CardHeader>
          <CardContent class="space-y-2">
            <div v-if="pendingTodos.length === 0" class="text-center py-8 text-muted-foreground">
              <CheckCircle2 class="mx-auto h-8 w-8 mb-2" />
              <p>No pending tasks!</p>
            </div>
            <div
              v-for="todo in pendingTodos"
              :key="todo.id"
              class="flex items-center gap-3 p-3 rounded-lg border bg-card hover:bg-accent/50 transition-colors"
            >
              <Button
                variant="ghost"
                size="sm"
                @click="toggleTodo(todo.id)"
                class="h-5 w-5 p-0 rounded-full border-2 border-muted-foreground hover:border-primary"
              >
                <span class="sr-only">Mark as complete</span>
              </Button>
              <div class="flex-1">
                <p class="font-medium">{{ todo.title }}</p>
                <p v-if="todo.description" class="text-sm text-muted-foreground">
                  {{ todo.description }}
                </p>
              </div>
              <Badge :variant="getPriorityVariant(todo.priority)">
                {{ todo.priority }}
              </Badge>
              <Button
                variant="ghost"
                size="sm"
                @click="deleteTodo(todo.id)"
                class="h-8 w-8 p-0 text-destructive hover:text-destructive"
              >
                <Trash2 class="h-4 w-4" />
                <span class="sr-only">Delete todo</span>
              </Button>
            </div>
          </CardContent>
        </Card>

        <!-- Completed Todos -->
        <Card>
          <CardHeader>
            <CardTitle class="flex items-center gap-2">
              <CheckCircle2 class="h-5 w-5" />
              Completed Tasks
            </CardTitle>
          </CardHeader>
          <CardContent class="space-y-2">
            <div v-if="completedTodos.length === 0" class="text-center py-8 text-muted-foreground">
              <Clock class="mx-auto h-8 w-8 mb-2" />
              <p>No completed tasks yet!</p>
            </div>
            <div
              v-for="todo in completedTodos"
              :key="todo.id"
              class="flex items-center gap-3 p-3 rounded-lg border bg-card hover:bg-accent/50 transition-colors opacity-75"
            >
              <Button
                variant="ghost"
                size="sm"
                @click="toggleTodo(todo.id)"
                class="h-5 w-5 p-0 rounded-full bg-primary text-primary-foreground"
              >
                <Check class="h-3 w-3" />
                <span class="sr-only">Mark as incomplete</span>
              </Button>
              <div class="flex-1">
                <p class="font-medium line-through">{{ todo.title }}</p>
                <p v-if="todo.description" class="text-sm text-muted-foreground line-through">
                  {{ todo.description }}
                </p>
              </div>
              <Badge variant="secondary"> Completed </Badge>
              <Button
                variant="ghost"
                size="sm"
                @click="deleteTodo(todo.id)"
                class="h-8 w-8 p-0 text-destructive hover:text-destructive"
              >
                <Trash2 class="h-4 w-4" />
                <span class="sr-only">Delete todo</span>
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>

    <!-- Add Todo Modal -->
    <div
      v-if="showAddModal"
      class="fixed inset-0 bg-black/80 flex items-center justify-center p-4 z-50"
      @click.self="closeAddModal"
    >
      <Card class="w-full max-w-md">
        <CardHeader>
          <CardTitle>Add New Todo</CardTitle>
          <CardDescription>Create a new task to stay organized</CardDescription>
        </CardHeader>
        <CardContent class="space-y-4">
          <div>
            <label class="text-sm font-medium">Task Title</label>
            <Input v-model="newTodo.title" placeholder="Enter task title" />
          </div>
          <div>
            <label class="text-sm font-medium">Description (optional)</label>
            <Input v-model="newTodo.description" placeholder="Enter task description" />
          </div>
          <div>
            <label class="text-sm font-medium">Priority</label>
            <select
              v-model="newTodo.priority"
              class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:border-ring focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
            >
              <option value="low">Low</option>
              <option value="medium">Medium</option>
              <option value="high">High</option>
            </select>
          </div>
        </CardContent>
        <CardFooter class="flex gap-2">
          <Button variant="outline" @click="closeAddModal"> Cancel </Button>
          <Button @click="addTodo" :disabled="!newTodo.title"> Add Todo </Button>
        </CardFooter>
      </Card>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { toast } from 'vue-sonner'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  CardFooter,
} from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import Button from '@/components/ui/button/Button.vue'
import Input from '@/components/ui/input/Input.vue'
import { Plus, Clock, CheckCircle2, Check, Trash2 } from 'lucide-vue-next'

interface Todo {
  id: number
  title: string
  description: string
  completed: boolean
  priority: 'low' | 'medium' | 'high'
  createdAt: Date
}

const todos = ref<Todo[]>([
  {
    id: 1,
    title: 'Complete project documentation',
    description: 'Write comprehensive docs for the Vue project',
    completed: false,
    priority: 'high',
    createdAt: new Date(),
  },
  {
    id: 2,
    title: 'Review pull requests',
    description: 'Check and approve pending PRs',
    completed: true,
    priority: 'medium',
    createdAt: new Date(),
  },
  {
    id: 3,
    title: 'Update dependencies',
    description: 'Upgrade to latest versions',
    completed: false,
    priority: 'low',
    createdAt: new Date(),
  },
])

const showAddModal = ref(false)
const newTodo = ref({
  title: '',
  description: '',
  priority: 'medium' as const,
})

const completedTodos = computed(() => todos.value.filter((todo) => todo.completed))
const pendingTodos = computed(() => todos.value.filter((todo) => !todo.completed))

const getPriorityVariant = (priority: string) => {
  switch (priority) {
    case 'high':
      return 'destructive'
    case 'medium':
      return 'default'
    case 'low':
      return 'secondary'
    default:
      return 'secondary'
  }
}

const openAddModal = () => {
  showAddModal.value = true
}

const closeAddModal = () => {
  showAddModal.value = false
  newTodo.value = {
    title: '',
    description: '',
    priority: 'medium',
  }
}

const addTodo = () => {
  if (!newTodo.value.title) return

  const todo: Todo = {
    id: Date.now(),
    title: newTodo.value.title,
    description: newTodo.value.description,
    completed: false,
    priority: newTodo.value.priority,
    createdAt: new Date(),
  }

  todos.value.push(todo)
  closeAddModal()
  toast.success('Todo added successfully!')
}

const toggleTodo = (id: number) => {
  const todo = todos.value.find((t) => t.id === id)
  if (todo) {
    todo.completed = !todo.completed
    toast.success(todo.completed ? 'Todo completed!' : 'Todo marked as pending')
  }
}

const deleteTodo = (id: number) => {
  const index = todos.value.findIndex((t) => t.id === id)
  if (index > -1) {
    todos.value.splice(index, 1)
    toast.success('Todo deleted successfully!')
  }
}
</script>
