// packages/create-scaffa/templates/react/backbone/src/modules/home/HomeView.tsx
import api from '@/api';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useQueryClient } from '@tanstack/react-query';
import i18next from 'i18next';
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';

const HomeView = () => {
	const { t } = useTranslation();
	const changeLanguage = (lng: string) => {
		i18next.changeLanguage(lng);
	};
	const [input, setInput] = useState('');

	const queryClient = useQueryClient();
	const productsQuery = api.products.getProducts.useQuery();
	const todosQuery = api.todos.getTodos.useInfiniteQuery();
	const addProductMutation = api.products.addProduct.useMutation({
		onSuccess: (data) => {
			toast.success('Product added successfully');
			queryClient.setQueryData(['products'], (oldData: ProductType[]) => {
				return [...oldData, data];
			});
			setInput('');
		}
	});

	const addProduct = () => {
		if (!input) {
			toast.error('Please enter a product name');
			return;
		}
		addProductMutation.mutate({
			title: input,
			description: 'Test',
			category: 'Test',
			price: 129.99,
			discountPercentage: 15,
			rating: 4.5,
			stock: 200,
			tags: ['test', 'testing'],
			brand: 'TestBrand',
			sku: 'TestSKU123',
			weight: 0.3, // in kg
			dimensions: {
				width: 18, // in cm
				height: 20, // in cm
				depth: 8 // in cm
			}
		});
	};

	return (
		<div>
			<h1 className="">Template: react-backbone</h1>
			<p>Tech Stack: React + Shadcn UI</p>
			<p>{t('common.hello')}</p>
			<div className="flex gap-2">
				<Button onClick={() => changeLanguage('en')}>English</Button>
				<Button onClick={() => changeLanguage('mm')}>Myanmar</Button>
			</div>

			<div className="flex space-x-2  my-3 ">
				<Input
					disabled={addProductMutation.isPending}
					className="w-[200px]"
					placeholder="Product Name"
					value={input}
					onChange={(e) => setInput(e.target.value)}
				/>
				<Button disabled={addProductMutation.isPending} onClick={addProduct}>
					Add Product
				</Button>
			</div>

			<h2>Products</h2>
			{productsQuery.isLoading ? (
				<p>Loading...</p>
			) : (
				<div>
					{productsQuery.data?.map((item) => (
						<div key={item.id}>
							{item.id}. {item.title}
						</div>
					))}
				</div>
			)}

			<hr className="my-5"></hr>

			<h2>Todos</h2>
			<div>
				{todosQuery.data?.map((todo, todoIndex) => (
					<div key={todo.id}>
						{todoIndex + 1} . {todo.todo}
					</div>
				))}
			</div>
			{todosQuery.hasNextPage ? (
				<Button
					onClick={() => {
						todosQuery.fetchNextPage();
					}}
				>
					Next
				</Button>
			) : (
				'No more data...'
			)}
		</div>
	);
};

export default HomeView;

// packages/create-makro/templates/vue-std/src/modules/home/HomeView.vue
<script setup lang="ts">
import api from '@/api'
import Button from '@/components/ui/button/Button.vue'
import Input from '@/components/ui/input/Input.vue'
import { useQueryClient } from '@tanstack/vue-query'
import { ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { toast } from 'vue-sonner'

const { t, locale } = useI18n()
const changeLanguage = (lang: string) => {
  locale.value = lang
}

const queryClient = useQueryClient()

const { data, isLoading } = api.products.getProducts.useQuery()
const input = ref('')

const { mutate, isPending } = api.products.addProduct.useMutation({
  onSuccess: (product) => {
    queryClient.setQueryData(['products'], (oldData: ProductType[]) => {
      return [...oldData, product]
    })
    input.value = ''
    toast.success('Product added successfully!')
  },
})

const addProduct = () => {
  if (!input.value) return
  mutate({
    title: input.value,
    description: 'Test',
    category: 'Test',
    price: 129.99,
    discountPercentage: 15,
    rating: 4.5,
    stock: 200,
    tags: ['test', 'testing'],
    brand: 'TestBrand',
    sku: 'TestSKU123',
    weight: 0.3, // in kg
    dimensions: {
      width: 18, // in cm
      height: 20, // in cm
      depth: 8, // in cm
    },
  })
}
</script>

<template>
  <section class="container">
    <h1>{{ t('common.hello') }}</h1>
    <p>Welcome to the Home page</p>
    <div class="flex gap-2">
      <Button @click="changeLanguage('en')">English</Button>
      <Button @click="changeLanguage('mm')">Myanmar</Button>
    </div>

    <br />

    <div class="flex gap-2">
      <Input
        :disabled="isPending"
        class="w-40"
        v-model="input"
        placeholder="Type something..."
        aria-label="input field"
      />
      <Button :disabled="isPending" @click="addProduct()">Add Product</Button>
    </div>

    <br />

    <div v-if="isLoading">Loading...</div>
    <div v-else>
      <div v-for="(product, index) in data" :key="product.id">
        <p>{{ index + 1 + '.' + product.title }}</p>
      </div>
    </div>
  </section>
</template>
