// packages/templates/vue-std/src/modules/home/HomeView.vue
<script setup lang="ts">
import api from '@/api';
import { useI18n } from 'vue-i18n';

  const {t, locale} = useI18n();
  const changeLanguage = (lang: string) => {
    locale.value = lang;
  };

  const {data,isLoading} = api.products.getProducts.useQuery();
</script>

<template>
  <section class="container">
    <h1>{{ t("common.hello") }}</h1>
    <p>Welcome to the Home page</p>
    <div class="flex gap-2">
      <button class="bg-yellow-400 text-black h-8 px-2 rounded-md font-medium" @click="changeLanguage('en')">English</button>
      <button class="bg-yellow-400 text-black h-8 px-2 rounded-md font-medium" @click="changeLanguage('mm')">Myanmar</button>
    </div>

    <br/>

    <div v-if="isLoading">Loading...</div>
    <div v-else>
      <div v-for="product in data" :key="product.id">
        <p>{{ product.title }}</p>
      </div>
    </div>
  </section>
</template>

// packages/templates/react-std/src/modules/home/HomeView.tsx
import api from "@/api";
import { Button } from "@/components/ui/button";
import i18next from "i18next";
import { useTranslation } from "react-i18next";

const HomeView = () => {
	const { t } = useTranslation();
	const changeLanguage = (lng: string) => {
		i18next.changeLanguage(lng);
	};
	const productsQuery  = api.products.getProducts.useQuery();
	return (
		<div>
			<h1 className="">Template: React-std</h1>
			<p>Tech Stack: React + Shadcn UI</p>
			<p>{t("common.hello")}</p>
			<div className="flex gap-2">
				<Button onClick={() => changeLanguage("en")}>English</Button>
				<Button onClick={() => changeLanguage("mm")}>Myanmar</Button>
			</div>

			{productsQuery.isLoading ? (
				<p>Loading...</p>
			) : (
				<div>
					{productsQuery.data?.map((item) => (
						<div key={item.id}>{item.title}</div>
					))}
				</div>
			)}
		</div>
	);
};

export default HomeView;
