// packages/create-scaffa/templates/vue/src/components/ThemeToggle.vue
<template>
  <Button variant="ghost" size="icon" @click="toggleTheme" class="h-9 w-9">
    <Sun class="h-4 w-4 rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" />
    <Moon class="absolute h-4 w-4 rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" />
    <span class="sr-only">Toggle theme</span>
  </Button>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { Sun, Moon } from 'lucide-vue-next'
import Button from '@/components/ui/button/Button.vue'

const isDark = ref(false)

const toggleTheme = () => {
  isDark.value = !isDark.value
  updateTheme()
}

const updateTheme = () => {
  if (isDark.value) {
    document.documentElement.classList.add('dark')
    localStorage.setItem('theme', 'dark')
  } else {
    document.documentElement.classList.remove('dark')
    localStorage.setItem('theme', 'light')
  }
}

const initTheme = () => {
  const savedTheme = localStorage.getItem('theme')
  const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches

  if (savedTheme === 'dark' || (!savedTheme && prefersDark)) {
    isDark.value = true
  } else {
    isDark.value = false
  }

  updateTheme()
}

onMounted(() => {
  initTheme()
})
</script>

// src/lib/components/ThemeToggle.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	let isDarkMode = $state<boolean | undefined>(undefined);

	onMount(() => {
		isDarkMode = localStorage.getItem('scaffa:theme') !== 'light' ? true : false;
	});
	function toggleTheme() {
		isDarkMode = !isDarkMode;
		localStorage.setItem('scaffa:theme', isDarkMode ? 'dark' : 'light');
		document.documentElement.classList.toggle('light', !isDarkMode);
	}
</script>

<button
	onclick={toggleTheme}
	class="w-8 h-8 flex justify-center items-center text-2xl"
>
	{#if isDarkMode === true}
		<i class="icon-[line-md--sunny-outline-to-moon-loop-transition] bg-light"></i>
	{:else if isDarkMode === false}
		<i class="icon-[solar--sun-2-linear] text-[#f2ba02]"></i>
	{:else}
		<i></i>
	{/if}
</button>
